// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRjZnSs6mdX_6mNuZyDmnMtLxXc7NhFjI',
    appId: '1:528429262090:web:ec39dcd8295fd8fb0846f3',
    messagingSenderId: '528429262090',
    projectId: 'test-chat-app-ryuji',
    authDomain: 'test-chat-app-ryuji.firebaseapp.com',
    storageBucket: 'test-chat-app-ryuji.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMkNP9mPCeiQaT_M9SzASyKSVvAtBhwQg',
    appId: '1:528429262090:android:72b5f86e1dd5b4230846f3',
    messagingSenderId: '528429262090',
    projectId: 'test-chat-app-ryuji',
    storageBucket: 'test-chat-app-ryuji.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTQ5bh5YtqpNiADYYsQk1IF4OYV7mTqQs',
    appId: '1:528429262090:ios:3b39dd090f9f450e0846f3',
    messagingSenderId: '528429262090',
    projectId: 'test-chat-app-ryuji',
    storageBucket: 'test-chat-app-ryuji.appspot.com',
    iosClientId: '528429262090-o06haehl33ejca07a90r5rpbure2s3ff.apps.googleusercontent.com',
    iosBundleId: 'com.example.testChatApp',
  );
}
